Repository Kotlin/kotlinx-rpc, pull requests merged in 2025-05, with the labels that each got.

#337 Update Kotlin to 2.1.21
  README.md
  docs/pages/kotlinx-rpc/topics/versions.topic
  docs/pages/kotlinx-rpc/v.list
  versions-root/kotlin-versions-lookup.csv
  versions-root/libs.versions.toml
Labels: dependencies

#338 Change strict mode to level ERROR by default
  compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/StrictMode.kt
  compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/checkers/diagnostics/RpcDiagnosticRendererFactory.kt
  docs/pages/kotlinx-rpc/topics/strict-mode.topic
  gradle-plugin/src/main/kotlin/kotlinx/rpc/Extensions.kt
  krpc/krpc-client/build.gradle.kts
  krpc/krpc-core/build.gradle.kts
  krpc/krpc-test/build.gradle.kts
  tests/compiler-plugin-tests/src/test/kotlin/kotlinx/rpc/codegen/test/services/ExtensionRegistrarConfigurator.kt
Labels: breaking, deprecation

#339 Release 0.7.0
  .github/workflows/docs.yml
  CHANGELOG.md
  README.md
  docs/pages/kotlinx-rpc/help-versions.json
  docs/pages/kotlinx-rpc/v.list
  docs/pages/kotlinx-rpc/writerside.cfg
  samples/ktor-all-platforms-app/gradle/libs.versions.toml
  samples/ktor-android-app/gradle/libs.versions.toml
  samples/ktor-web-app/gradle/libs.versions.toml
  samples/simple-ktor-app/build.gradle.kts
  versions-root/libs.versions.toml
Labels: release

#340 Advance version to 0.8.0-SNAPSHOT
  versions-root/libs.versions.toml
Labels: housekeeping

#342 Update README.md to use non-suspend flows
  README.md
Labels: housekeeping
