Repository Kotlin/kotlinx-rpc, pull requests merged in 2025-01, with the labels that each got.

#254 Added missing aliases for migration
  core/src/commonMain/kotlin/kotlinx/rpc/RpcCall.kt
  core/src/commonMain/kotlin/kotlinx/rpc/RpcClient.kt
Labels: bug

#258 Fixed @Rpc annotation diagnostic
  compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/FirRpcPredicates.kt
  compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/checkers/FirRpcAnnotationChecker.kt
  compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/checkers/diagnostics/FirRpcDiagnostics.kt
  compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/checkers/diagnostics/RpcDiagnosticRendererFactory.kt
  tests/compiler-plugin-tests/src/test-gen/kotlinx/rpc/codegen/test/runners/BoxTestGenerated.java
  tests/compiler-plugin-tests/src/test-gen/kotlinx/rpc/codegen/test/runners/DiagnosticTestGenerated.java
  tests/compiler-plugin-tests/src/testData/diagnostics/rpcChecked.kt
Labels: bug

#264 [gRPC] Fix compilation for the plugin
  compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/FirRpcUtils.kt
Labels: bug

#266 Fix typo in README.md
  README.md
Labels: docs

#265 Added monitor app for deps publication
  .gitignore
  monitor/main.py
  monitor/requirements.txt
Labels: housekeeping
