Repository Kotlin/kotlinx-rpc, pull requests merged in 2025-07, with the labels that each got.

#374 Propagate transport coroutine context
  krpc/krpc-server/src/commonMain/kotlin/kotlinx/rpc/krpc/server/KrpcServer.kt
  krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/CoroutineContextPropagationTest.kt
  krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/LocalTransport.kt
  krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/cancellation/CancellationToolkit.kt
  krpc/krpc-test/src/jvmTest/kotlin/kotlinx/rpc/krpc/test/api/WireSamplingTestScope.kt
Labels: bug

#377 Added artifacts validation
  build.gradle.kts
  compiler-plugin/build.gradle.kts
  docs/environment.md
  dokka-plugin/build.gradle.kts
  gradle-conventions/src/main/kotlin/compiler-specific-module.gradle.kts
  gradle-conventions/src/main/kotlin/conventions-publishing.gradle.kts
  gradle-conventions/src/main/kotlin/conventions-root.gradle.kts
  gradle-conventions/src/main/kotlin/util/other/capitalized.kt
  gradle-conventions/src/main/kotlin/util/other/maybeNamed.kt
  gradle-conventions/src/main/kotlin/util/targets/configure.kt
  gradle-conventions/src/main/kotlin/util/targets/nativePublication.kt
  gradle-conventions/src/main/kotlin/util/tasks/validatePublishedArtifacts.kt
  gradle-plugin/build.gradle.kts
  gradle/artifacts/publishApplePublicationToBuildRepoRepository.txt
  gradle/artifacts/publishBomPublicationToBuildRepoRepository.txt
  gradle/artifacts/publishJsPublicationToBuildRepoRepository.txt
  gradle/artifacts/publishJvmPublicationToBuildRepoRepository.txt
  gradle/artifacts/publishKotlinMultiplatformPublicationToBuildRepoRepository.txt
  gradle/artifacts/publishLinuxPublicationToBuildRepoRepository.txt
  gradle/artifacts/publishMavenPublicationToBuildRepoRepository.txt
  gradle/artifacts/publishWasmJsPublicationToBuildRepoRepository.txt
  gradle/artifacts/publishWindowsPublicationToBuildRepoRepository.txt
  validatePublishedArtifacts.sh
Labels: infra

#381 Fix dokka API button for all modules
  gradle-conventions/src/main/kotlin/conventions-dokka-spec.gradle.kts
  gradle-conventions/src/main/kotlin/conventions-root.gradle.kts
  gradle-conventions/src/main/kotlin/util/dokka.kt
Labels: docs

#387 Update version for 0.9.0-SNAPSHOT
  versions-root/libs.versions.toml
Labels: housekeeping

#391 Update gRPC doc
  docs/pages/kotlinx-rpc/topics/grpc-server.topic
  docs/pages/kotlinx-rpc/topics/grpc-services.topic
Labels: docs

#396 Make KtorRpcClient inherit KrpcClient
  krpc/krpc-ktor/krpc-ktor-client/api/krpc-ktor-client.api
  krpc/krpc-ktor/krpc-ktor-client/api/krpc-ktor-client.klib.api
  krpc/krpc-ktor/krpc-ktor-client/src/commonMain/kotlin/kotlinx/rpc/krpc/ktor/client/KtorRpcClient.kt
Labels: bug

#393 gRPC: Ktor Plugin
  docs/pages/kotlinx-rpc/topics/platforms.topic
  grpc/grpc-core/api/grpc-core.api
  grpc/grpc-core/api/grpc-core.klib.api
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/GrpcClient.kt
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/GrpcServer.kt
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/ManagedChannel.kt
  grpc/grpc-core/src/jsMain/kotlin/kotlinx/rpc/grpc/ManagedChannel.js.kt
  grpc/grpc-core/src/jvmMain/kotlin/kotlinx/rpc/grpc/ManagedChannel.jvm.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/ManagedChannel.native.kt
  grpc/grpc-core/src/wasmJsMain/kotlin/kotlinx/rpc/grpc/ManagedChannel.wasmJs.kt
  grpc/grpc-ktor-server-test/api/grpc-ktor-server-test.api
  grpc/grpc-ktor-server-test/build.gradle.kts
  grpc/grpc-ktor-server-test/gradle.properties
  grpc/grpc-ktor-server-test/src/test/kotlin/kotlinx/rpc/grpc/ktor/server/test/TestServer.kt
  grpc/grpc-ktor-server-test/src/test/proto/ktor-test-service.proto
  grpc/grpc-ktor-server-test/src/test/resources/logback.xml
  grpc/grpc-ktor-server/api/grpc-ktor-server.api
  grpc/grpc-ktor-server/api/grpc-ktor-server.klib.api
  grpc/grpc-ktor-server/build.gradle.kts
  grpc/grpc-ktor-server/gradle.properties
  grpc/grpc-ktor-server/src/commonMain/kotlin/kotlinx/rpc/grpc/ktor/server/Server.kt
  settings.gradle.kts
Labels: feature

#401 Release 0.9.1
  .github/workflows/docs.yml
  CHANGELOG.md
  README.md
  docs/pages/kotlinx-rpc/help-versions.json
  docs/pages/kotlinx-rpc/topics/changelog.md
  docs/pages/kotlinx-rpc/v.list
  docs/pages/kotlinx-rpc/writerside.cfg
  kotlin-js-store/package-lock.json
  kotlin-js-store/wasm/package-lock.json
  samples/ktor-all-platforms-app/gradle/libs.versions.toml
  samples/ktor-android-app/gradle/libs.versions.toml
  samples/ktor-web-app/gradle/libs.versions.toml
  samples/simple-ktor-app/build.gradle.kts
  versions-root/libs.versions.toml
Labels: release

#410 Tasks caching
  gradle-plugin/src/main/kotlin/kotlinx/rpc/buf/tasks/BufGenerateTask.kt
  gradle-plugin/src/main/kotlin/kotlinx/rpc/buf/tasks/GenerateBufGenYaml.kt
  gradle-plugin/src/main/kotlin/kotlinx/rpc/buf/tasks/GenerateBufYaml.kt
  gradle-plugin/src/main/kotlin/kotlinx/rpc/grpc/DefaultGrpcExtension.kt
  gradle-plugin/src/main/kotlin/kotlinx/rpc/proto/DefaultProtoSourceSet.kt
  gradle-plugin/src/main/kotlin/kotlinx/rpc/proto/ProcessProtoFiles.kt
  gradle-plugin/src/main/kotlin/kotlinx/rpc/proto/derictory.kt
  gradle-plugin/src/main/kotlin/kotlinx/rpc/util/files.kt
  kotlin-js-store/package-lock.json
  kotlin-js-store/wasm/package-lock.json
Labels: bug

#407 Advance version to 0.10.0-SNAPSHOT
  versions-root/libs.versions.toml
Labels: housekeeping

#414 Added jvm codecs implementations
  grpc/grpc-core/build.gradle.kts
  grpc/grpc-core/gradle.properties
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/internal/WireDecoder.kt
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/internal/WireEncoder.kt
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/internal/readPacked.kt
  grpc/grpc-core/src/commonTest/kotlin/kotlinx/rpc/grpc/internal/WireCodecTest.kt
  grpc/grpc-core/src/jsMain/kotlin/kotlinx/rpc/grpc/internal/readPacked.js.kt
  grpc/grpc-core/src/jvmMain/kotlin/kotlinx/rpc/grpc/internal/WireDecoder.jvm.kt
  grpc/grpc-core/src/jvmMain/kotlin/kotlinx/rpc/grpc/internal/WireEncoder.jvm.kt
  grpc/grpc-core/src/jvmMain/kotlin/kotlinx/rpc/grpc/internal/WireSize.jvm.kt
  grpc/grpc-core/src/jvmMain/kotlin/kotlinx/rpc/grpc/internal/readPacked.jvm.kt
  grpc/grpc-core/src/jvmTest/kotlin/kotlinx/rpc/grpc/core/test/TestReferenceService.kt
  grpc/grpc-core/src/jvmTest/proto/repeated.proto
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/WireDecoder.native.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/WireEncoder.native.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/readPacked.native.kt
  grpc/grpc-core/src/nativeTest/kotlin/kotlinx/rpc/grpc/internal/WireCodecTest.native.kt
  grpc/grpc-core/src/wasmJsMain/kotlin/kotlinx/rpc/grpc/internal/readPacked.wasmJs.kt
  grpc/grpc-ktor-server/gradle.properties
  protoc-gen/src/main/kotlin/kotlinx/rpc/protobuf/ModelToKotlinGenerator.kt
Labels: feature
