Repository Kotlin/kotlinx-rpc, pull requests merged in 2025-09, with the labels that each got.

#472 protobuf: Add support for deprecated groups
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Any.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Api.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Duration.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Empty.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/FieldMask.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/SourceContext.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Struct.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Timestamp.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Type.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Wrappers.kt
  protobuf/protobuf-core/src/commonMain/kotlin/kotlinx/rpc/protobuf/internal/WireDecoder.kt
  protobuf/protobuf-core/src/commonMain/kotlin/kotlinx/rpc/protobuf/internal/WireEncoder.kt
  protobuf/protobuf-core/src/commonTest/kotlin/kotlinx/rpc/protobuf/test/ProtosTest.kt
  protobuf/protobuf-core/src/commonTest/proto/groups.proto
  protobuf/protobuf-core/src/jvmMain/kotlin/kotlinx/rpc/protobuf/internal/WireEncoder.jvm.kt
  protobuf/protobuf-core/src/nativeMain/kotlin/kotlinx/rpc/protobuf/internal/WireEncoder.native.kt
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/codeRequestToModel.kt
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/model/FieldType.kt
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/model/model.kt
  protoc-gen/protobuf/src/main/kotlin/kotlinx/rpc/protoc/gen/ModelToProtobufKotlinCommonGenerator.kt
  setup_protocscope.sh
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf/conformance/_rpc_internal/Conformance.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/editions/proto3/_rpc_internal/TestMessagesProto3Editions.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/proto3/_rpc_internal/TestMessagesProto3.kt
  tests/protobuf-conformance/src/test/kotlin/kotlinx/rpc/protoc/gen/test/ConformanceTest.kt
Labels: feature

#473 protobuf: Enable all conformance tests
  .github/workflows/protobuf-conformance.yml
  protobuf/protobuf-core/src/commonMain/kotlin/kotlinx/rpc/protobuf/internal/ProtobufException.kt
  protobuf/protobuf-core/src/commonTest/proto/test_map.proto
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/model/model.kt
  protoc-gen/protobuf/src/main/kotlin/kotlinx/rpc/protoc/gen/ModelToProtobufKotlinCommonGenerator.kt
  tests/protobuf-conformance/build.gradle.kts
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/edition2023/TestMessagesEdition2023.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/edition2023/_rpc_internal/TestMessagesEdition2023.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/editions/proto2/TestMessagesProto2Editions.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/editions/proto2/_rpc_internal/TestMessagesProto2Editions.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/proto2/TestMessagesProto2.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/proto2/_rpc_internal/TestMessagesProto2.kt
  tests/protobuf-conformance/src/main/kotlin/kotlinx/rpc/protoc/gen/test/ConformanceClient.kt
  tests/protobuf-conformance/src/test/kotlin/kotlinx/rpc/protoc/gen/test/ConformanceTest.kt
Labels: feature

#477 grpc: Fix onReady() listener delegation (KRPC-220)
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/NativeServerCall.kt
Labels: bug

#474 grpc: Add KMP sample project
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/utils.kt
  protobuf/protobuf-core/build.gradle.kts
  samples/grpc-kmp-app/.gitignore
  samples/grpc-kmp-app/README.md
  samples/grpc-kmp-app/build.gradle.kts
  samples/grpc-kmp-app/composeApp/build.gradle.kts
  samples/grpc-kmp-app/composeApp/src/commonMain/composeResources/drawable/compose-multiplatform.xml
  samples/grpc-kmp-app/composeApp/src/commonMain/kotlin/kotlinx/rpc/sample/App.kt
  samples/grpc-kmp-app/composeApp/src/iosMain/kotlin/kotlinx/rpc/sample/MainViewController.kt
  samples/grpc-kmp-app/composeApp/src/jvmMain/kotlin/kotlinx/rpc/sample/main.kt
  samples/grpc-kmp-app/gradle.properties
  samples/grpc-kmp-app/gradle/libs.versions.toml
  samples/grpc-kmp-app/gradle/wrapper/gradle-wrapper.jar
  samples/grpc-kmp-app/gradle/wrapper/gradle-wrapper.properties
  samples/grpc-kmp-app/gradlew
  samples/grpc-kmp-app/gradlew.bat
  samples/grpc-kmp-app/iosApp/Configuration/Config.xcconfig
  samples/grpc-kmp-app/iosApp/iosApp.xcodeproj/project.pbxproj
  samples/grpc-kmp-app/iosApp/iosApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  samples/grpc-kmp-app/iosApp/iosApp/Assets.xcassets/AccentColor.colorset/Contents.json
  samples/grpc-kmp-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  samples/grpc-kmp-app/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/app-icon-1024.png
  samples/grpc-kmp-app/iosApp/iosApp/Assets.xcassets/Contents.json
  samples/grpc-kmp-app/iosApp/iosApp/ContentView.swift
  samples/grpc-kmp-app/iosApp/iosApp/Info.plist
  samples/grpc-kmp-app/iosApp/iosApp/Preview Content/Preview Assets.xcassets/Contents.json
  samples/grpc-kmp-app/iosApp/iosApp/iOSApp.swift
  samples/grpc-kmp-app/server/build.gradle.kts
  samples/grpc-kmp-app/server/src/main/kotlin/kotlinx/rpc/sample/Application.kt
  samples/grpc-kmp-app/server/src/main/kotlin/kotlinx/rpc/sample/MessageServiceImpl.kt
  samples/grpc-kmp-app/server/src/main/resources/logback.xml
  samples/grpc-kmp-app/settings.gradle.kts
  samples/grpc-kmp-app/shared/build.gradle.kts
  samples/grpc-kmp-app/shared/src/commonMain/kotlin/kotlinx/rpc/sample/Constants.kt
  samples/grpc-kmp-app/shared/src/commonMain/kotlin/kotlinx/rpc/sample/Greeting.kt
  samples/grpc-kmp-app/shared/src/commonMain/kotlin/kotlinx/rpc/sample/Platform.kt
  samples/grpc-kmp-app/shared/src/commonMain/proto/chat.proto
  samples/grpc-kmp-app/shared/src/iosMain/kotlin/kotlinx/rpc/sample/Platform.ios.kt
  samples/grpc-kmp-app/shared/src/jvmMain/kotlin/kotlinx/rpc/sample/Platform.jvm.kt
Labels: docs

#487 Grpc.Method Annotation
  cinterop-c/build_target.sh
  compiler-plugin/compiler-plugin-backend/src/main/kotlin/kotlinx/rpc/codegen/extension/RpcStubGenerator.kt
  compiler-plugin/compiler-plugin-backend/src/main/kotlin/kotlinx/rpc/codegen/extension/ServiceDeclaration.kt
  compiler-plugin/compiler-plugin-common/src/main/kotlin/kotlinx/rpc/codegen/common/Names.kt
  compiler-plugin/compiler-plugin-k2/src/main/kotlin/kotlinx/rpc/codegen/checkers/FirGrpcServiceDeclarationChecker.kt
  compiler-plugin/compiler-plugin-k2/src/main/kotlin/kotlinx/rpc/codegen/checkers/FirRpcServiceDeclarationChecker.kt
  compiler-plugin/compiler-plugin-k2/src/main/kotlin/kotlinx/rpc/codegen/checkers/diagnostics/FirRpcDiagnostics.kt
  compiler-plugin/compiler-plugin-k2/src/main/kotlin/kotlinx/rpc/codegen/checkers/diagnostics/RpcDiagnosticRendererFactory.kt
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/annotations/Grpc.kt
  grpc/grpc-core/src/commonTest/kotlin/kotlinx/rpc/grpc/test/GrpcAnnotationsTest.kt
  grpc/grpc-core/src/commonTest/proto/idempotency.proto
  protoc-gen/grpc/src/main/kotlin/kotlinx/rpc/protoc/gen/grpc/ModelToGrpcKotlinCommonGenerator.kt
  tests/compiler-plugin-tests/src/main/kotlin/kotlinx/rpc/codegen/test/Grpc.kt
  tests/compiler-plugin-tests/src/test-gen/kotlinx/rpc/codegen/test/runners/BoxTestGenerated.java
  tests/compiler-plugin-tests/src/test-gen/kotlinx/rpc/codegen/test/runners/DiagnosticTestGenerated.java
  tests/compiler-plugin-tests/src/testData/box/grpc.fir.ir.txt
  tests/compiler-plugin-tests/src/testData/diagnostics/grpc.fir.txt
  tests/compiler-plugin-tests/src/testData/diagnostics/grpc.kt
Labels: feature

#478 Kotlin 2.2.20
  README.md
  compiler-plugin/compiler-plugin-cli/src/main/kotlin/kotlinx/rpc/codegen/RpcCommandLineProcessor.kt
  compiler-plugin/compiler-plugin-cli/src/main/kotlin/kotlinx/rpc/codegen/pluginId.kt
  compiler-plugin/compiler-plugin-cli/src/main/kotlin/kotlinx/rpc/codegen/registerRpcExtensions.kt
  compiler-plugin/compiler-plugin-cli/src/main/templates/kotlinx/rpc/codegen/CompilerPluginRegistrar.kt
  compiler-plugin/compiler-plugin-k2/src/main/kotlin/kotlinx/rpc/codegen/FirRpcServiceGenerator.kt
  compiler-plugin/gradle.properties
  docs/pages/kotlinx-rpc/topics/versions.topic
  docs/pages/kotlinx-rpc/v.list
  dokka-plugin/gradle.properties
  dowload_kotlin_master.sh
  gradle-conventions/src/main/kotlin/util/tasks/npm.kt
  gradle-plugin/gradle.properties
  gradle-plugin/src/main/kotlin/kotlinx/rpc/RpcPluginConst.kt
  gradle.properties
  kotlin-js-store/package-lock.json
  kotlin-js-store/wasm/package-lock.json
  kotlin-js-store/wasm/yarn.lock
  kotlin-js-store/yarn.lock
  krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTransportTestBase.kt
  versions-root/libs.versions.toml
Labels: feature

#479 Added Ktor closure tests and Cancellation tests, + minor fixes
  docs/environment.md
  gradle-conventions/src/main/kotlin/util/tasks/npm.kt
  kotlin-js-store/wasm/yarn.lock
  kotlin-js-store/yarn.lock
  krpc/krpc-client/src/commonMain/kotlin/kotlinx/rpc/krpc/client/KrpcClient.kt
  krpc/krpc-core/src/commonMain/kotlin/kotlinx/rpc/krpc/internal/KrpcConnector.kt
  krpc/krpc-core/src/commonMain/kotlin/kotlinx/rpc/krpc/internal/KrpcEndpoint.kt
  krpc/krpc-core/src/commonMain/kotlin/kotlinx/rpc/krpc/internal/KrpcReceiveHandler.kt
  krpc/krpc-ktor/krpc-ktor-core/src/jvmTest/kotlin/kotlinx/rpc/krpc/ktor/KtorTransportTest.kt
  krpc/krpc-logging/src/commonMain/kotlin/kotlinx/rpc/krpc/internal/logging/RpcInternalCommonLogger.kt
  krpc/krpc-server/src/commonMain/kotlin/kotlinx/rpc/krpc/server/KrpcServer.kt
  krpc/krpc-server/src/commonMain/kotlin/kotlinx/rpc/krpc/server/internal/KrpcServerService.kt
  krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/BackPressureTest.kt
  krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/cancellation/CancellationService.kt
  krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/cancellation/CancellationTest.kt
  tests/compiler-plugin-tests/src/testData/box/customParameterTypes.kt
  tests/compiler-plugin-tests/src/testData/box/flowParameter.kt
  tests/compiler-plugin-tests/src/testData/box/multiModule.kt
  tests/compiler-plugin-tests/src/testData/box/simple.kt
  tests/compiler-plugin-tests/src/testData/diagnostics/checkedAnnotation.kt
  tests/compiler-plugin-tests/src/testData/diagnostics/rpcChecked.kt
  tests/compiler-plugin-tests/src/testData/diagnostics/rpcService.kt
  tests/compiler-plugin-tests/src/testData/diagnostics/strictMode.kt
  tests/krpc-protocol-compatibility-tests/src/test/kotlin/kotlinx/rpc/krpc/test/compat/KrpcProtocolCompatibilityTestsBase.kt
  versions-root/libs.versions.toml
Labels: housekeeping

#482 Added docs for release
  docs/pages/kotlinx-rpc/rpc.tree
  docs/pages/kotlinx-rpc/topics/0-10-0.topic
  docs/pages/kotlinx-rpc/topics/configuration.topic
  docs/pages/kotlinx-rpc/topics/krpc-ktor.topic
Labels: docs

#488 Pb comments
  .github/workflows/protobuf-conformance.yml
  .github/workflows/protobuf-well-known-types.yml
  gradle-plugin/api/gradle-plugin.api
  gradle-plugin/src/main/kotlin/kotlinx/rpc/Extensions.kt
  gradle-plugin/src/main/kotlin/kotlinx/rpc/buf/BufExtensions.kt
  gradle-plugin/src/main/kotlin/kotlinx/rpc/protoc/DefaultProtoSourceSet.kt
  gradle-plugin/src/main/kotlin/kotlinx/rpc/protoc/DefaultProtocExtension.kt
  grpc/grpc-core/src/commonTest/proto/comments.proto
  protobuf/protobuf-core/build.gradle.kts
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/Any.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/Api.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/Duration.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/Empty.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/FieldMask.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/SourceContext.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/Struct.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/Timestamp.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/Type.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/Wrappers.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Any.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Api.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Duration.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Empty.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/FieldMask.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/SourceContext.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Struct.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Timestamp.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Type.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Wrappers.kt
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/AModelToKotlinCommonGenerator.kt
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/CodeGenerator.kt
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/ProtocGenPlugin.kt
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/codeRequestToModel.kt
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/comments.kt
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/model/FieldType.kt
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/model/model.kt
  protoc-gen/grpc/src/main/kotlin/kotlinx/rpc/protoc/gen/grpc/GrpcProtocGenPlugin.kt
  protoc-gen/grpc/src/main/kotlin/kotlinx/rpc/protoc/gen/grpc/ModelToGrpcKotlinCommonGenerator.kt
  protoc-gen/protobuf/src/main/kotlin/kotlinx/rpc/protoc/gen/ModelToProtobufKotlinCommonGenerator.kt
  protoc-gen/protobuf/src/main/kotlin/kotlinx/rpc/protoc/gen/ProtobufProtocGenPlugin.kt
  tests/protobuf-conformance/build.gradle.kts
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf/conformance/Conformance.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf/conformance/_rpc_internal/Conformance.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/edition2023/TestMessagesEdition2023.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/edition2023/_rpc_internal/TestMessagesEdition2023.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/editions/proto2/TestMessagesProto2Editions.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/editions/proto2/_rpc_internal/TestMessagesProto2Editions.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/editions/proto3/TestMessagesProto3Editions.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/editions/proto3/_rpc_internal/TestMessagesProto3Editions.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/proto2/TestMessagesProto2.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/proto2/_rpc_internal/TestMessagesProto2.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/proto3/TestMessagesProto3.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/proto3/_rpc_internal/TestMessagesProto3.kt
Labels: feature

#489 Support deprecated option in PB
  grpc/grpc-core/src/commonTest/proto/options.proto
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/AModelToKotlinCommonGenerator.kt
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/CodeGenerator.kt
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/codeRequestToModel.kt
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/model/model.kt
  protoc-gen/grpc/src/main/kotlin/kotlinx/rpc/protoc/gen/grpc/ModelToGrpcKotlinCommonGenerator.kt
  protoc-gen/protobuf/src/main/kotlin/kotlinx/rpc/protoc/gen/ModelToProtobufKotlinCommonGenerator.kt
Labels: feature

#490 PB: Added hasCode, equals and toString support
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/Struct.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/Type.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Any.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Api.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Duration.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Empty.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/FieldMask.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/SourceContext.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Struct.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Timestamp.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Type.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Wrappers.kt
  protobuf/protobuf-core/src/commonMain/kotlin/kotlinx/rpc/protobuf/internal/BitSet.kt
  protobuf/protobuf-core/src/commonMain/kotlin/kotlinx/rpc/protobuf/internal/InternalMessage.kt
  protobuf/protobuf-core/src/commonTest/kotlin/kotlinx/rpc/protobuf/test/ComparisonTest.kt
  protobuf/protobuf-core/src/commonTest/kotlin/kotlinx/rpc/protobuf/test/ToStringTest.kt
  protobuf/protobuf-core/src/commonTest/proto/equals.proto
  protobuf/protobuf-core/src/commonTest/proto/to_string.proto
  protoc-gen/protobuf/src/main/kotlin/kotlinx/rpc/protoc/gen/ModelToProtobufKotlinCommonGenerator.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf/conformance/Conformance.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf/conformance/_rpc_internal/Conformance.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/edition2023/TestMessagesEdition2023.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/edition2023/_rpc_internal/TestMessagesEdition2023.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/editions/proto2/TestMessagesProto2Editions.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/editions/proto2/_rpc_internal/TestMessagesProto2Editions.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/editions/proto3/TestMessagesProto3Editions.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/editions/proto3/_rpc_internal/TestMessagesProto3Editions.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/proto2/TestMessagesProto2.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/proto2/_rpc_internal/TestMessagesProto2.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/proto3/TestMessagesProto3.kt
  tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/proto3/_rpc_internal/TestMessagesProto3.kt
Labels: feature
