Repository Kotlin/kotlinx-rpc, pull requests merged in 2025-08, with the labels that each got.

#416 Fix how we create 'publishMavenArtifact' tasks
  gradle-conventions/build.gradle.kts
  gradle-conventions/src/main/kotlin/conventions-kotlin-version.gradle.kts
  gradle-conventions/src/main/kotlin/conventions-publishing.gradle.kts
  gradle-conventions/src/main/kotlin/conventions-root.gradle.kts
  gradle-plugin/build.gradle.kts
Labels: housekeeping

#405 Add a doc for KMP source sets with gRPC
  docs/pages/kotlinx-rpc/topics/grpc-configuration.topic
Labels: docs

#424 Fix LV and signing
  gradle-conventions/src/main/kotlin/conventions-publishing.gradle.kts
  krpc/krpc-test/build.gradle.kts
  krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTransportTestBase.kt
Labels: housekeeping

#428 Added gRPC service generation to the compiler plugin
  compiler-plugin/compiler-plugin-backend/src/main/kotlin/kotlinx/rpc/codegen/extension/RpcIrContext.kt
  compiler-plugin/compiler-plugin-backend/src/main/kotlin/kotlinx/rpc/codegen/extension/RpcStubGenerator.kt
  compiler-plugin/compiler-plugin-backend/src/main/kotlin/kotlinx/rpc/codegen/extension/ServiceDeclaration.kt
  core/api/core.api
  core/api/core.klib.api
  core/src/commonMain/kotlin/kotlinx/rpc/RpcCall.kt
  core/src/commonMain/kotlin/kotlinx/rpc/descriptor/RpcServiceDescriptor.kt
  core/src/commonMain/kotlin/kotlinx/rpc/descriptor/RpcServiceDescriptorDefault.kt
  grpc/grpc-codec-kotlinx-serialization/api/grpc-codec-kotlinx-serialization.api
  grpc/grpc-codec-kotlinx-serialization/api/grpc-codec-kotlinx-serialization.klib.api
  grpc/grpc-codec-kotlinx-serialization/build.gradle.kts
  grpc/grpc-codec-kotlinx-serialization/src/commonMain/kotlin/kotlinx/rpc/grpc/codec/kotlinx/serialization/KotlinxSerializationCodecResolver.kt
  grpc/grpc-codec/api/grpc-codec.api
  grpc/grpc-codec/api/grpc-codec.klib.api
  grpc/grpc-codec/build.gradle.kts
  grpc/grpc-codec/src/commonMain/kotlin/kotlinx/rpc/grpc/codec/MessageCodec.kt
  grpc/grpc-codec/src/commonMain/kotlin/kotlinx/rpc/grpc/codec/WithCodec.kt
  grpc/grpc-core/api/grpc-core.api
  grpc/grpc-core/api/grpc-core.klib.api
  grpc/grpc-core/build.gradle.kts
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/GrpcClient.kt
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/GrpcServer.kt
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/annotations/Grpc.kt
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/descriptor/GrpcServiceDescriptor.kt
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/internal/MethodDescriptor.kt
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/internal/suspendClientCalls.kt
  grpc/grpc-core/src/commonTest/kotlin/kotlinx/rpc/grpc/RawClientServerTest.kt
  grpc/grpc-core/src/commonTest/kotlin/kotlinx/rpc/grpc/pb/ProtosTest.kt
  grpc/grpc-core/src/commonTest/kotlin/kotlinx/rpc/grpc/service/GrpcService.kt
  grpc/grpc-core/src/jvmMain/kotlin/kotlinx/rpc/grpc/internal/MethodDescriptor.jvm.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/MethodDescriptor.native.kt
  grpc/grpc-ktor-server/api/grpc-ktor-server.api
  grpc/grpc-ktor-server/api/grpc-ktor-server.klib.api
  grpc/grpc-ktor-server/src/commonMain/kotlin/kotlinx/rpc/grpc/ktor/server/Server.kt
  krpc/krpc-client/src/commonMain/kotlin/kotlinx/rpc/krpc/client/KrpcClient.kt
  krpc/krpc-server/src/commonMain/kotlin/kotlinx/rpc/krpc/server/internal/KrpcServerService.kt
  protoc-gen/src/main/kotlin/kotlinx/rpc/protobuf/ModelToKotlinCommonGenerator.kt
  settings.gradle.kts
  tests/compiler-plugin-tests/build.gradle.kts
  tests/compiler-plugin-tests/src/test/kotlin/kotlinx/rpc/codegen/test/runners/AbstractBoxTest.kt
  tests/compiler-plugin-tests/src/test/kotlin/kotlinx/rpc/codegen/test/runners/AbstractDiagnosticTest.kt
  tests/compiler-plugin-tests/src/test/kotlin/kotlinx/rpc/codegen/test/runners/BaseTestRunner.kt
  tests/compiler-plugin-tests/src/test/kotlin/kotlinx/rpc/codegen/test/services/ExtensionRegistrarConfigurator.kt
  tests/compiler-plugin-tests/src/testData/box/customParameterTypes.fir.ir.txt
  tests/compiler-plugin-tests/src/testData/box/flowParameter.fir.ir.txt
  tests/compiler-plugin-tests/src/testData/box/multiModule.fir.ir.txt
  tests/compiler-plugin-tests/src/testData/box/simple.fir.ir.txt
Labels: feature

#431 Add collect once check for client streams
  krpc/krpc-server/src/commonMain/kotlin/kotlinx/rpc/krpc/server/internal/ServerStreamContext.kt
  krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestService.kt
  krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestServiceBackend.kt
  krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTransportTestBase.kt
Labels: bug

#432 Fix diagnostic rendering for compiler plugins checkers
  compiler-plugin/compiler-plugin-k2/src/main/kotlin/kotlinx/rpc/codegen/FirRpcExtensionRegistrar.kt
  compiler-plugin/compiler-plugin-k2/src/main/kotlin/kotlinx/rpc/codegen/checkers/diagnostics/FirRpcDiagnostics.kt
  compiler-plugin/compiler-plugin-k2/src/main/kotlin/kotlinx/rpc/codegen/checkers/diagnostics/RpcDiagnosticRendererFactory.kt
  compiler-plugin/compiler-plugin-k2/src/main/templates/kotlinx/rpc/codegen/checkers/diagnostics/RpcKtDiagnosticsContainer.kt
Labels: bug

#440 Update strict-mode.topic
  docs/pages/kotlinx-rpc/topics/strict-mode.topic
Labels: docs

#441 Bump compat-patrouille version
  versions-root/libs.versions.toml
Labels: dependencies

#450 Update grpc-configuration.topic
  docs/pages/kotlinx-rpc/topics/grpc-configuration.topic
Labels: docs

#445 fix wrong unchecked null cast (potential NPE)
  krpc/krpc-client/src/commonMain/kotlin/kotlinx/rpc/krpc/client/KrpcClient.kt
  krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestService.kt
  krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestServiceBackend.kt
  krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTransportTestBase.kt
  krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/TestClass.kt
Labels: bug

#449 Added support for Well-Known Types
  .github/workflows/protobuf-well-known-types.yml
  gradle-plugin/api/gradle-plugin.api
  gradle-plugin/src/main/kotlin/kotlinx/rpc/buf/tasks/BufGenerateTask.kt
  gradle-plugin/src/main/kotlin/kotlinx/rpc/internal/configureLocalProtocGenDevelopmentDependency.kt
  gradle-plugin/src/main/kotlin/kotlinx/rpc/protoc/DefaultProtoSourceSet.kt
  gradle-plugin/src/main/kotlin/kotlinx/rpc/protoc/DefaultProtocExtension.kt
  gradle-plugin/src/main/kotlin/kotlinx/rpc/protoc/ProtoSourceSet.kt
  gradle-plugin/src/main/kotlin/kotlinx/rpc/protoc/ProtocExtension.kt
  gradle-plugin/src/main/kotlin/kotlinx/rpc/protoc/pluginJars.kt
  gradle-plugin/src/test/kotlin/kotlinx/rpc/GrpcJvmProjectTest.kt
  gradle-plugin/src/test/resources/projects/GrpcJvmProjectTest/can_add_custom_protoc_plugins/build.gradle.kts
  gradle-plugin/src/test/resources/projects/GrpcJvmProjectTest/custom_protoc_plugins_must_declare_an_artifact/build.gradle.kts
  protobuf/protobuf-core/build.gradle.kts
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/Any.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/Api.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/Duration.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/Empty.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/FieldMask.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/SourceContext.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/Struct.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/Timestamp.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/Type.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/Wrappers.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Any.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Api.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Duration.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Empty.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/FieldMask.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/SourceContext.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Struct.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Timestamp.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Type.kt
  protobuf/protobuf-core/src/commonMain/generated-code/kotlin-multiplatform/com/google/protobuf/kotlin/_rpc_internal/Wrappers.kt
  protobuf/protobuf-core/src/commonMain/kotlin/com/google/protobuf/kotlin/duration.kt
  protobuf/protobuf-core/src/commonMain/kotlin/com/google/protobuf/kotlin/timestamp.kt
  protobuf/protobuf-core/src/commonMain/proto/well-known-types.proto
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/AModelToKotlinCommonGenerator.kt
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/CodeGenerator.kt
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/ProtocGenPlugin.kt
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/codeRequestToModel.kt
  protoc-gen/grpc/src/main/kotlin/kotlinx/rpc/protoc/gen/grpc/GrpcProtocGenPlugin.kt
  protoc-gen/grpc/src/main/kotlin/kotlinx/rpc/protoc/gen/grpc/ModelToGrpcKotlinCommonGenerator.kt
  protoc-gen/protobuf/src/main/kotlin/kotlinx/rpc/protoc/gen/ModelToProtobufKotlinCommonGenerator.kt
  protoc-gen/protobuf/src/main/kotlin/kotlinx/rpc/protoc/gen/ProtobufProtocGenPlugin.kt
  tests/protobuf-conformance/build.gradle.kts
Labels: feature

#452 grpc-native: Support client calls on native
  cinterop-c/BUILD.bazel
  cinterop-c/MODULE.bazel
  cinterop-c/include/grpcpp_c.h
  cinterop-c/include/kgrpc.h
  cinterop-c/include/protowire.h
  cinterop-c/src/grpcpp_c.cpp
  cinterop-c/src/kgrpc.cpp
  cinterop-c/src/protowire.cpp
  grpc/grpc-core/build.gradle.kts
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/internal/ClientCall.kt
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/internal/MethodDescriptor.kt
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/internal/suspendClientCalls.kt
  grpc/grpc-core/src/commonTest/kotlin/kotlinx/rpc/grpc/test/RawClientTest.kt
  grpc/grpc-core/src/commonTest/proto/echo_grpc.proto
  grpc/grpc-core/src/commonTest/proto/helloworld.proto
  grpc/grpc-core/src/nativeInterop/cinterop/libgrpcpp_c.def
  grpc/grpc-core/src/nativeInterop/cinterop/libkgrpc.def
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/ManagedChannel.native.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/Status.native.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/StatusException.native.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/CallbackFuture.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/ClientCall.native.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/CompletionQueue.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/GrpcCallOptions.native.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/GrpcContext.native.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/MethodDescriptor.native.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/NativeClientCall.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/NativeGrpcLibrary.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/NativeManagedChannel.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/ServerCall.native.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/bridge/GrpcByteBuffer.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/bridge/GrpcClient.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/bridge/GrpcSlice.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/utils.kt
  grpc/grpc-core/src/nativeTest/kotlin/kotlinx/rpc/grpc/internal/CoreTest.kt
  grpc/grpc-core/src/nativeTest/kotlin/kotlinx/rpc/grpc/test/BridgeTest.kt
  protobuf/protobuf-core/build.gradle.kts
  protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/codeRequestToModel.kt
  protoc-gen/grpc/src/main/kotlin/kotlinx/rpc/protoc/gen/grpc/ModelToGrpcKotlinCommonGenerator.kt
Labels: feature

#438 Use compat-patrouille for compatibility settings
  build.gradle.kts
  compiler-plugin/build.gradle.kts
  dokka-plugin/build.gradle.kts
  gradle-conventions/build.gradle.kts
  gradle-conventions/src/main/kotlin/conventions-gradle-doctor.gradle.kts
  gradle-conventions/src/main/kotlin/conventions-jvm.gradle.kts
  gradle-conventions/src/main/kotlin/conventions-kmp.gradle.kts
  gradle-conventions/src/main/kotlin/conventions-kotlin-version.gradle.kts
  gradle-conventions/src/main/kotlin/empty.gradle.kts
  gradle-conventions/src/main/kotlin/util/targets/configure.kt
  gradle-plugin/build.gradle.kts
  kotlin-js-store/package-lock.json
  kotlin-js-store/wasm/package-lock.json
  krpc/krpc-test/build.gradle.kts
  versions-root/libs.versions.toml
Labels: infra

#456 Kotlin 2.2.10
  README.md
  compiler-plugin/compiler-plugin-k2/src/main/templates/kotlinx/rpc/codegen/FirVersionSpecificApiImpl.kt
  docs/pages/kotlinx-rpc/topics/versions.topic
  docs/pages/kotlinx-rpc/v.list
  kotlin-js-store/package-lock.json
  kotlin-js-store/wasm/package-lock.json
  versions-root/libs.versions.toml
Labels: feature

#457 grpc: Fix service names in the generated descriptor
  compiler-plugin/compiler-plugin-backend/src/main/kotlin/kotlinx/rpc/codegen/extension/RpcDeclarationScanner.kt
  compiler-plugin/compiler-plugin-backend/src/main/kotlin/kotlinx/rpc/codegen/extension/RpcStubGenerator.kt
  compiler-plugin/compiler-plugin-backend/src/main/kotlin/kotlinx/rpc/codegen/extension/ServiceDeclaration.kt
  compiler-plugin/compiler-plugin-k2/src/main/kotlin/kotlinx/rpc/codegen/checkers/FirRpcStrictModeClassChecker.kt
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/Status.kt
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/annotations/Grpc.kt
  grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/internal/suspendClientCalls.kt
  grpc/grpc-core/src/commonTest/kotlin/kotlinx/rpc/grpc/test/CoreClientTest.kt
  grpc/grpc-core/src/commonTest/kotlin/kotlinx/rpc/grpc/test/RawClientTest.kt
  grpc/grpc-core/src/commonTest/kotlin/kotlinx/rpc/grpc/test/proto/GrpcProtoTest.kt
  grpc/grpc-core/src/commonTest/kotlin/kotlinx/rpc/grpc/test/proto/JavaPackageOptionTest.kt
  grpc/grpc-core/src/commonTest/proto/echo_grpc.proto
  grpc/grpc-core/src/commonTest/proto/helloworld_grpc.proto
  grpc/grpc-core/src/commonTest/proto/with_java_pkg_grpc.proto
  grpc/grpc-core/src/jvmMain/kotlin/kotlinx/rpc/grpc/Status.jvm.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/Status.native.kt
  grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/NativeClientCall.kt
  protoc-gen/grpc/src/main/kotlin/kotlinx/rpc/protoc/gen/grpc/ModelToGrpcKotlinCommonGenerator.kt
  tests/compiler-plugin-tests/src/main/kotlin/kotlinx/rpc/codegen/test/Grpc.kt
  tests/compiler-plugin-tests/src/testData/box/grpc.fir.ir.txt
  tests/compiler-plugin-tests/src/testData/box/grpc.fir.txt
  tests/compiler-plugin-tests/src/testData/box/grpc.kt
Labels: bug

#458 grpc-native: Add support for iOS
  cinterop-c/.bazelrc
  cinterop-c/.gitignore
  cinterop-c/BUILD.bazel
  cinterop-c/MODULE.bazel
  cinterop-c/MODULE.bazel.lock
  cinterop-c/build_target.sh
  gradle-conventions/src/main/kotlin/util/cinterop.kt
  grpc/grpc-core/build.gradle.kts
  grpc/grpc-core/gradle.properties
  grpc/grpc-core/src/nativeInterop/cinterop/libkgrpc.def
  protobuf/protobuf-core/build.gradle.kts
  protobuf/protobuf-core/gradle.properties
  protobuf/protobuf-core/src/nativeInterop/cinterop/libprotowire.def
  versions-root/libs.versions.toml
Labels: feature, infra
